name: Daily Portfolio Update

on:
  schedule:
    # Run at 6:30 PM Eastern Time (22:30 UTC)
    - cron: "30 22 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.11.1.1273

      - name: Run Portfolio Update
        run: clj -M run-portfolio.clj
        env:
          OANDA_LIVE_OR_DEMO: ${{ secrets.OANDA_LIVE_OR_DEMO }}
          OANDA_DEMO_ACCOUNT_ID: ${{ secrets.OANDA_DEMO_ACCOUNT_ID }}
          OANDA_LIVE_ACCOUNT_ID: ${{ secrets.OANDA_LIVE_ACCOUNT_ID }}
          OANDA_DEMO_KEY: ${{ secrets.OANDA_DEMO_KEY }}
          OANDA_LIVE_KEY: ${{ secrets.OANDA_LIVE_KEY }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_SECRET_KEY: ${{ secrets.BINANCE_SECRET_KEY }}

      - name: Record update timestamp
        run: echo "Portfolio updated at $(date)" >> portfolio-updates.log

      - name: Commit log
        uses: EndBug/add-and-commit@v9
        with:
          add: "portfolio-updates.log"
          message: "Update portfolio log [skip ci]"
          default_author: github_actions
